import type { Metadata } from "next";
import "../globals.css";
import { AppProvider } from "@/context/AppContext";
import { loadSettings } from "@/sanity/loader/loadQuery";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await loadSettings();

  if (!settings.data) {
    return (
      <div className="text-center">You don&rsquo;t have settings yet, </div>
    );
  }

  return (
    <AppProvider>
      {children}
      <Footer {...settings.data.footer} />
    </AppProvider>
  );
}
